[dev]
node1.lab.local ntp_server=pool.ntp.org exam_sku=ex467 exam_taker=chris

[webserver]
node2.lab.local

[aap]
control.lab.local
hub.lab.local

[dev:vars]
ntp_server=pool.ntp.org
exam_sku=ex467
exam_taker=chris
